#! /bin/bash

sudo cp change-wallpaper.sh /usr/local/bin/change-wallpaper.sh
sudo chmod 755 /usr/local/bin/change-wallpaper.sh
sudo chown root:root /usr/local/bin/change-wallpaper.sh

# Autostart
mkdir -p ~/.config/autostart
cp change-wallpaper.desktop ~/.config/autostart/change-wallpaper.desktop
chmod 644 ~/.config/autostart/change-wallpaper.desktop